### ISSUE TITLE
Add flags to make notes public (or private)

### ISSUE THREAD

**Issue by kennydo** [sixninetynine/not#8]
It'd be cool if there was a `--public` flag so that the created note is automatically shared publicly, and the share-able URL is printed to stdout.

`--public` would make a note public if it wasn't already public, and it can be made private again by calling `not --private`.

I think we'd use [shareNote](https://dev.evernote.com/doc/reference/NoteStore.html#Fn_NoteStore_shareNote) and [stopSharing](https://dev.evernote.com/doc/reference/NoteStore.html#Fn_NoteStore_stopSharingNote).

**Comment by lorencarvalho** [comment]
I can't think of a way to make this work that isn't super annoying :/
